### ISSUE TITLE
support for nested directories

### ISSUE THREAD

**Issue by justRu** [Netatwork-de/gulp-create-tsindex#1]
It would be nice to have a support for nested directories.

That is, given the following structure:
`component\compA\compA.ts`
`component\compB\compB.ts`
I want to generate `index.ts` in 'components\index.ts' with the following content:
`export * from "./compA/compA.ts";`
`export * from "./compB/compB.ts";`

So, maybe you can add a parameter: directory for `index.ts`. The following snippet works for me (`indexFileDir` is the parameter):

`contentBuilder.append('export * from "./');`
`var relativePath = path.relative(indexFileDir, file.path);`
`var pathWithoutExt = relativePath.slice(0, -ext.length).replace('\\', '/');`
`contentBuilder.append(pathWithoutExt);`
`contentBuilder.appendLine('";');`

**Comment by SSchnietz** [comment]
The support for nested directories has been added with the laster 1.03 version.
