### ISSUE TITLE
Support for .tsx files

### ISSUE THREAD

**Issue by Morcatko** [Netatwork-de/gulp-create-tsindex#2]
This is a great plugin, but it lacks support for react/tsx files.

The final/generated index can be always .ts (no matter what was the source), the only missing functionality is reading of *.tsx files.

Changing this
`if (ext === ".ts" && ext2 !== ".d")`
to this will do the trick
`if ((ext === ".ts" && ext2 !== ".d") || (ext === ".tsx"))`

Thanks

**Comment by SSchnietz** [comment]
I've added you code to version 1.0.4.
